dadJokes = [
	[["What rock group has four men that don\'t sing"], ["Mount Rushmore."]],
	[["What do sprinters eat before a race"], ["Nothing, they fast!"]],
	[["What concert costs just 45 cents"], ["50 Cent featuring Nickelback!"]],
	[["What do you call a mac \'n\' cheese that gets all up in your face"], ["Too close for comfort food!"]],
	[["Why couldn\'t the bicycle stand up by itself"], ["It was two tired!"]],
	[["Did you hear about the restaurant on the moon"], ["Great food, no atmosphere!"]],
	[["Why do melons have weddings"], ["Because they cantaloupe!"]],
	[["What happens when you go to the bathroom in France"], ["European."]],
	[["What\'s the difference between a poorly dressed man on a tricycle and a well-dressed man on a bicycle"], ["Attire!"]],
	[["How many apples grow on a tree"], ["All of them!"]],
	[["Did you hear the rumor about butter"], ["Well, I\'m not going to spread it!"]],
	[["Did you hear about the guy who invented Lifesavers"], [" They say he made a mint!"]],
	[["Why did the old man fall in the well"], ["Because he couldn\'t see that well!"]],
	[["What do you call a factory that sells passable products"], ["A satisfactory!"]],
	[["Why did the invisible man turn down the job offer"], ["He couldn\'t see himself doing it!"]],
	[["Want to hear a joke about construction"], ["I\'m still working on it!"]],
	[["How does Moses make his coffee"], ["Hebrews it."]],
	[["Why did the scarecrow win an award"], ["Because he was outstanding in his field!"]],
	[["What do you call a fish with two knees"], ["A two-knee fish!"]],
	[["Why do you never see elephants hiding in trees"], ["Because they\'re so good at it!"]],
	[["How does a penguin build its house"], ["Igloos it together!"]],
	[["Why don\'t skeletons ever go trick or treating"], ["Because they have no body to go with!"]],
	[["What\'s ET short for"], ["Because he\'s only got tiny legs!"]],
	[["What\'s brown and sticky"], ["A stick!"]],
	[["Can February march"], ["No, but April may!"]],
	[["What\'s orange and sounds like a parrot"], ["A carrot!"]],
	[["How do you make a Kleenex dance"], ["Put some boogie in it!"]],
	[["Why is Peter Pan always flying"], ["He neverlands!"]],
	[["What\'s a ninja\'s favorite type of shoes"], ["Sneakers!"]],
	[["What do Santa\'s elves listen to ask they work"], ["Wrap music!"]],
	[["Did you hear about the bacon cheeseburger who couldn\'t stop telling jokes"], ["It was on a roll."]],
	[["Why was the coach yelling at a vending machine"], ["He wanted his quarter back."]],
	[["Why do vampires seem sick"], ["They\'re always coffin."]],
	[["Did I tell you the time I fell in love during a backflip"], ["I was heels over head!"]],
	[["Did you hear about the Italian chef who died"], ["He pasta way!"]],
	[["What do you call a donkey with only three legs"], ["A wonkey!"]],
	[["What do you call a guy with a rubber toe"], ["Roberto!"]],
	[["What rhymes with boo and stinks"], ["You!"]],
	[["Which U.S. state is famous for its extra-small soft drinks"], ["Minnesota!"]],
	[["What did the Ranch say when someone opened the refrigerator door"], ["Close the door, I\'m dressing!"]],
	[["Why do trees seem suspicious on sunny days"], ["They just seem a little shady!"]],
	[["What did the policeman say to his belly button"], ["You\'re under a vest!"]],
	[["What do you call a fake noodle"], ["An Impasta!"]],
	[["Why did the math book look so sad"], ["Because of all of its problems!"]],
	[["What does the cell say to his sister when she steps on his toe"], ["Oh my toe sis!"]],
	[["How do you tell the difference between a bull and a milk cow"], ["It is either one or the utter."]],
	[["What do scholars eat when they\'re hungry"], ["Academia nuts."]],
	[["What do you call an ant that has been shunned by his community"], ["A socially dissed ant."]],
	[["When does a joke become a dad joke"], ["When it becomes apparent."]]
]
